ingress:
  enabled: true
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    ## allow large bom.xml uploads:
    #nginx.ingress.kubernetes.io/proxy-body-size: 10m
  host: deptrack.example.org
frontend:
  replicaCount: 1
  service:
    type: NodePort
