on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn clean install
      - name: Copy JAR to target directory
        run: cp target/*.jar ${{github.workspace}}/target/
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  # sast:
  #   runs-on: ubuntu-latest
  #   name: Run unit tests and SAST scan on the source code
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-java@v3
  #     with:
  #       distribution: 'temurin'
  #       java-version: '17'
  #       cache: 'maven'
  #   - name: Build with Maven cloud
  #     run: mvn -B verify sonar:sonar -Dsonar.projectKey=vincennlin_devsecopsdiy -Dsonar.organization=vincennlin
  #       -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  #   env:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sbom:
    runs-on: ubuntu-latest
    name: Generate SBOM
    needs: depchecktest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Generate SBOM
        run: mvn cyclonedx:makeAggregateBom
      # - name: Copy SBOM to target directory
      #   run: cp target/bom.xml ${{github.workspace}}/target/bom.xml
      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: ${{github.workspace}}/target/bom.xml

  slscan:
    runs-on: ubuntu-latest
    needs: depchecktest
    name: Perform SL Scan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"
      - uses: actions/upload-artifact@master
        with:
          name: SLSCAN reports
          path: ${{github.workspace}}/reports
          
  build_and_push:
    name: Build & Push to DockerHub
    needs: slscan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17' 
          cache: 'maven'
      - name: Copy SBOM to Docker context
        run: cp ${{github.workspace}}/target/bom.xml .
      - name: Replace existing bom.xml in target directory
        run: mv bom.xml target/bom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image with Maven
        run: docker build -t vincennlin/devsecopsdiy:1.0 .
      - name: Docker Push to DockerHub
        run: docker push vincennlin/devsecopsdiy:1.0
